name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build frontend
      - name: Build frontend
        run: npm run build

      # 5. Upload dist/ to EC2 (temp folder inside ubuntu home)
      - name: Upload build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "~/deploy-temp/"

      # 6. Move into /var/www/html and restart nginx
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Cleaning old build..."
            sudo rm -rf /var/www/html/*
            echo "Deploying new build..."
            sudo cp -r ~/deploy-temp/* /var/www/html/
            rm -rf ~/deploy-temp/*
            echo "Restarting Nginx..."
            sudo systemctl restart nginx
            echo "✅ Deployment complete!"